export default {
    PATH_TO_INFO: 'return.OperationResult',
    PATH_TO_INFO_ARRAY: 'return.OperationResult.item',
    VALUE_NAME: '$value',
    PERSON_PUT_KEYS_LIST: [
        'LastName',
        'FirstName',
        'MiddleName',
        'TabNum',
        'Id',
        'CompanyId',
        'DepartmentId',
        'PositionId',
    ],
    PERSON_DEFAULT_KEYS_LIST: [
        'LastName',
        'FirstName',
        'MiddleName',
        'TabNum',
        'IsDismissed',
        'CompanyId',
        'DepartmentId',
        'PositionId',
    ],
    EVENT_KEYS_LIST: ['TabNum', 'Description', 'EventDate', 'EventTypeId', 'EventId', 'AccessPointId', 'PassMode'],
    CARD_KEYS_LIST: ['AccessLevelId', 'IsBlocked', 'PersonId', 'StartDate', 'EndDate'],
};
